# Generated by Django 4.0.2 on 2022-02-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='genre',
        ),
    ]
