# Generated by Django 4.0.2 on 2022-02-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='genre',
            new_name='transaction',
        ),
    ]
