# Generated by Django 4.0.2 on 2022-02-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_genre_market_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='market',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
